### ISSUE TITLE
syslog-ng missing in audit logging ?

### ISSUE THREAD

**Issue by rascherm** [telekom/tel-it-security-automation#2]
Is checking for `syslog-ng.conf` missing in audit.d logging ? 

https://github.com/telekom/tel-it-security-automation/blob/master/hardening-linux-server/vars/vars_linux(02)logging.yml

maybe something like `find /etc -name '*syslog*.conf' -type f -exec auditctl -w {} \;` would do.

**Comment by Schumburg** [comment]
As we not support syslog-ng in current version logging is also not enabled. We put this to our to do list as a reminder when we implement syslog-ng.
