### ISSUE TITLE
hardening-linux-server : req-007.2 error in case of missing file in check mode

### ISSUE THREAD

**Issue by C-F-A** [telekom/tel-it-security-automation#21]
I´ve executed the role in check mode and it aborts at req-007.2 as the checked files do not exist.
Tested with CentOS Linux release 7.9 Cloud Image.

TASK [./tel-it-security-automation-master/hardening-linux-server : req-007.2 add authorized users as only users able to modify at/cron] **************************************
failed: [10.102.131.137] (item=/etc/cron.allow) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/cron.allow", "msg": "Destination /etc/cron.allow does not exist !", "rc": 257}
failed: [10.102.131.137] (item=/etc/at.allow) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/at.allow", "msg": "Destination /etc/at.allow does not exist !", "rc": 257}

This could be fixed if for "req-007.2 add authorized users as only users able to modify at/cron" one more when condition is added:  - not ansible_check_mode

**Comment by hackerkreise** [comment]
This project will be archived.
