### ISSUE TITLE
hardening-linux-server : enable iptables service fails in check mode

### ISSUE THREAD

**Issue by C-F-A** [telekom/tel-it-security-automation#22]
I´ve executed the role in check mode and it aborts on v.
Tested with CentOS Linux release 7.9 Cloud Image.

TASK [./tel-it-security-automation-master/hardening-linux-server : enable iptables service for ipv4 (RedHat)] ****************************************************************
fatal: [10.102.131.137]: FAILED! => {"changed": false, "msg": "Could not find the requested service iptables.service: host"}

TASK [./tel-it-security-automation-master/hardening-linux-server : enable iptables service for ipv6 (RedHat)] ****************************************************************
fatal: [10.102.131.137]: FAILED! => {"changed": false, "msg": "Could not find the requested service ip6tables.service: host"}

iptables in installed, but seems no service exists for it.

**Comment by hackerkreise** [comment]
This project will be archived.
