### ISSUE TITLE
hardening-ssh: check for unsupported OS missing

### ISSUE THREAD

**Issue by C-F-A** [telekom/tel-it-security-automation#23]
In case the hardening-ssh role is executed on an unsupported OS no clear error message is given like in hardening-linux-server role.

It fails with:
TASK [./tel-it-security-automation-master/hardening-ssh : req-1-25.1 set configuration for sshd (req 1, 3 - 25)] *************************************************************
fatal: [10.102.141.132]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'os_sshd_conf_file' is undefined\n\nThe error appears to be in '/mnt/c/Temp/Huawei/mae/playbooks/demo/tel-it-security-automation-master/hardening-ssh/tasks/ssh(01)all.yml': line 34, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: req-1-25.1 set configuration for sshd (req 1, 3 - 25)\n  ^ here\n"}

Better would be to use the same function as in hardening-linux-server role:

- debug:
    msg: "family: {{ ansible_os_family }}; distro: {{ ansible_distribution }}; version {{ ansible_distribution_version }}"

# Stop playbook if Linux distro and version is not supported.
- fail:
    msg: "Your {{ansible_distribution}} is not supported!"
  when:
    - ansible_distribution != "RedHat"
    - ansible_distribution != "CentOS" 
    - ansible_distribution != "Amazon"
    - ansible_distribution != "Ubuntu" 
    - ansible_distribution != "SLES"

**Comment by hackerkreise** [comment]
This project will be archived.
