### ISSUE TITLE
same variable names used in both roles

### ISSUE THREAD

**Issue by C-F-A** [telekom/tel-it-security-automation#24]
I was using both roles within one playbook and it seemed to work fine, until I found problems with sftp, being sure I did not disable it.

It turned out that using a **vars_custom_config.yml** file configured for hardening-linux-server role was the problem.
Unfortunately the variables names for hardening-linux-server and hardening-ssh are the same even if for totally different functions / requirements.

Variables names should not be "**config_req_50**" but rather "**config_req_ssh_50**" and "**config_req_linux_50**".

**Comment by hackerkreise** [comment]
This project will be archived.
