### ISSUE TITLE
iptables rules seem not to work

### ISSUE THREAD

**Issue by C-F-A** [telekom/tel-it-security-automation#25]
Within CentOS7 I applied the hardening-linux-server role.

I changed the configuration to include a custom port (additional to 22) via vars_custom_config.yml file:
tcp_services:
  - "22"
  - "9090"

However the rules were done in wrong order (rule for 9090 was added after REJECT/DROP rule) leading to non reachable port 9090.

**Comment by hackerkreise** [comment]
This project will be archived.
